### ISSUE TITLE
(PROF. JORGE) CRIAR todas as issues conforme as atividades separadas por responsável

### ISSUE THREAD

**Issue by jlsilva01** [wguii/Trabalho_BD2_Aluguel_de_Equipamentos#2]
Cada atividade precisa ter uma issue vinculada.
Uma atividade executada sem ter uma issue criada, é uma atividade invisível, sem rastreio.

Criem as atividades e separem por responsável, por favor.

**Comment by wguii** [comment]
Issues criadas
