### ISSUE TITLE
(PROF. JORGE) VALIDAR as issues sem RESPONSÁVEL

### ISSUE THREAD

**Issue by jlsilva01** [wguii/Trabalho_BD2_Aluguel_de_Equipamentos#3]
Todas as issues precisarão ter um responsável por ela.

![lista_atividades_sem_responsavel](https://github.com/user-attachments/assets/03dfda82-f763-4211-8e82-f238020fcad1)

Validem as issues e efetuem as devidas correções.

**Comment by wguii** [comment]
Issues criadas e responsáveis designados
